[package]
name = "omochabank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
csv = "1.1"
num-traits = "0.2"
rust_decimal = "1.26"
serde = "1"